# Generated by Django 4.2.5 on 2023-10-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "est_description",
                    models.CharField(max_length=100, verbose_name="Description"),
                ),
                (
                    "est_amount",
                    models.DecimalField(
                        db_column="budget_expense_amt",
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Estimated Expense Amount (Ghs)",
                    ),
                ),
                (
                    "est_expense_date",
                    models.DateField(verbose_name="Estimated Date of Expense"),
                ),
                (
                    "est_expense_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.expensetype",
                    ),
                ),
            ],
        ),
    ]
