# Generated by Django 4.2.5 on 2023-10-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_rename_ext_date_time_budgetexpense_est_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetexpense",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
