# Generated by Django 4.2.5 on 2023-10-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_rename_is_completed_budgetexpense_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetexpense",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Status"),
        ),
    ]
