# Generated by Django 4.2.5 on 2023-10-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exp_source",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Expense Category"
                    ),
                ),
            ],
            options={
                "db_table": "ExpenseType",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exp_description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "exp_amount",
                    models.DecimalField(
                        db_column="expense_amount",
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Amount (Ghs)",
                    ),
                ),
                ("exp_date", models.DateField(verbose_name="Date of Expense")),
                ("exp_date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "exp_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.expensetype",
                    ),
                ),
            ],
        ),
    ]
