# Generated by Django 4.2.5 on 2023-10-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncomeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Source of Income"
                    ),
                ),
            ],
            options={
                "db_table": "IncomeType",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Income",
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Amount (Ghs)",
                    ),
                ),
                ("income_date", models.DateField(verbose_name="Date Income Received")),
                (
                    "income_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="income.incometype",
                    ),
                ),
            ],
            options={
                "db_table": "Income",
            },
        ),
    ]
