# Generated by Django 4.2.5 on 2023-10-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(
                db_column="Income",
                decimal_places=4,
                max_digits=7,
                verbose_name="Amount (Ghs)",
            ),
        ),
    ]
