# Generated by Django 4.2.5 on 2023-10-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_alter_income_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(
                db_column="Income",
                decimal_places=2,
                max_digits=7,
                verbose_name="Amount (Ghs)",
            ),
        ),
    ]
